api/urls.py
from django.conf.urls import include, url
from api.views import router
from api.views.app_execute_view import AppExecuteView
from api.views.app_purchase_view import AppPurchaseView
from api.views.login_view import LoginView
from api.views.order_view import OrderView
from api.views.register_view import RegisterView

urlpatterns = [
    url(r'^', include(router.urls, namespace='app')),
    url(r'^execute/', AppExecuteView.as_view(), name='execute'),
    url(r'^purchase/', AppPurchaseView.as_view(), name='purchase'),
    url(r'^orders/', OrderView.as_view(), name='orders'),
    url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^register/', RegisterView.as_view(), name='register'),
]

ilazy_web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'ilazy_web.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/', include('api.urls', namespace='apps')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

common/models.py
from django.db import models

# Create your models here.

common/templates/_footer_nav.html
{% load i18n %}
{% load url from future %}
<ul class="list-unstyled">
    <li class="pull-right">
        <a href="#top">{% trans "Back to top" %}</a>
    </li>
</ul>

common/templates/_notification.html
{% load bootstrap %}
{% if messages %}
    <div class="notifications">
        {% for message in messages %}
            {% render_message message %}
        {% endfor %}
    </div>
{% endif %}

common/templates/_notification_message.html
{% if "template" in message.tags_array %}
    {% include message.message %}
{% else %}
    <div class="alert alert-dismissable alert-{{ message.tags }}">
        {{ message }}
    </div>
{% endif %}

common/templates/_top_banner.html
{% load i18n %}
{% load url from future %}
<div class="page-header" id="banner">
    {% if show_top_banner %}
        <div class="row">
            <div class="col-lg-6">
                <h1><a href="{% url 'homepage' %}" title="{% trans "CouchDNA" %}" rel="home">{% trans "CouchDNA" %}</a>
                </h1>

                <p class="lead">
                    {% trans "CouchDNA" %}
                </p>
            </div>
        </div>
    {% endif %}
</div>

common/templates/_top_nav.html
{% load i18n %}
{% load common_tags %}

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a href="/" class="navbar-brand">{% trans "CouchDNA" %}</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                {% if user.is_provider %}
                    <li class="dropdown">
                        <a id="my-services" class="dropdown-toggle" data-toggle="dropdown" href="#">
                            {% trans "My Services" %}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'services:create' %}">New Service</a>
                            </li>
                            {% for service in user.service_set.all %}
                                {% if forloop.counter0 == 0 %}
                                    <li class="divider"></li>
                                {% endif %}
                                <li class="my-service" data-id="{{ service.id }}">
                                    <a href="{% url 'services:edit' service.id %}">{{ service.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" id="account-link" class="dropdown-toggle" data-toggle="dropdown">
                            {% include 'common/user_name_block.html' %}
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="logout" href="{% url 'accounts:logout' %}">{% trans 'Log out' %}</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li>
                        <a id="login-nav" href="{% url 'accounts:login' %}">{% trans "Log in" %}</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</div>

common/templates/base.html
<!DOCTYPE html>
{% load i18n %}
{% load staticfiles %}
<html>
<head>
    <title>{% block title %}Home{% endblock %} - {{ SITE_NAME }}</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="cache-control" content="public" />
    <meta name="robots" content="follow, all" />
    <meta name="language" content="{{ LANGUAGE_CODE }}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description"
          content="{% block meta-description %}{% trans 'CouchDNA' %}{% endblock %}" />
    <meta name="keywords" content="{% block meta-keywords %}{% endblock %}" />
    <meta name="author" content="Antipro.VN" />
    {% block meta %}{% endblock %}
    <link rel="pingback" href="/xmlrpc/" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <link rel="home" href="/" />
    {% block head-link %}
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'toastr/toastr.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    {% endblock %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="{% static 'jquery-cookie/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/head_define.js' %}"></script>
</head>
<body id="{% block page_id %}body{% endblock %}">
{% include '_top_nav.html' %}
<div class="container">
    {% include '_top_banner.html' %}
    {% block slider %}{% endblock %}
    <div id="content" class="hfeed">
        {% include '_notification.html' %}

        {% block content %}

        {% endblock %}
    </div>
    <footer>
        <div class="row">
            <div class="col-lg-12">
                {% include '_footer_nav.html' %}
                <p>
                    {% blocktrans %}Powered by <a href="/">CouchDNA</a>{% endblocktrans %}
                </p>
            </div>
        </div>
    </footer>
</div>

{% block footerjs %}
    <script src="{% static 'js/head_define.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'toastr/toastr.min.js' %}"></script>
    <script src="{% static 'js/foot_define.js' %}"></script>
{% endblock %}
</body>
</html>

common/templates/homepage.html
{% extends 'base.html' %}
{% load i18n %}